// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteCollection_RecyclingPlatform.Repositories.Data;

#nullable disable

namespace WasteCollectionRecyclingPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417064539_AddRewardPointTransactionsAndFinalRewardFields")]
    partial class AddRewardPointTransactionsAndFinalRewardFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompletedRequests")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("MonthlyCapacityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProcessedThisMonthKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictName")
                        .IsUnique();

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.CollectionRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<string>("CitizenName")
                        .HasColumnType("longtext");

                    b.Property<long?>("CollectorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CollectorName")
                        .HasColumnType("longtext");

                    b.Property<string>("CollectorPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long?>("WardId")
                        .HasColumnType("bigint");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("WardId");

                    b.ToTable("collection_requests", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.PasswordReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ResetTokenExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("password_resets", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.RewardPointTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("SourceRefId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("reward_point_transactions", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.VoucherCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("voucher_categories", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.VoucherCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UsedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("VoucherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("voucher_codes", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Ward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CollectedKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompletedRequests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Name")
                        .IsUnique();

                    b.ToTable("wards", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PointsPerKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("waste_categories", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("EstimatedTotalPoints")
                        .HasColumnType("int");

                    b.Property<int?>("FinalRewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("LocationText")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("RewardVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("Status");

                    b.ToTable("waste_reports", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("WasteReportId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WasteReportItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WasteReportId");

                    b.HasIndex("WasteReportItemId");

                    b.ToTable("waste_report_images", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EstimatedPoints")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedWeightKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("WasteCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("WasteReportId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WasteCategoryId");

                    b.HasIndex("WasteReportId");

                    b.ToTable("waste_report_items", (string)null);
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("WasteReportId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("WasteReportId");

                    b.ToTable("waste_report_status_histories", (string)null);
                });

            modelBuilder.Entity("ward_collectors", b =>
                {
                    b.Property<long>("CollectorsId")
                        .HasColumnType("bigint");

                    b.Property<long>("WardsId")
                        .HasColumnType("bigint");

                    b.HasKey("CollectorsId", "WardsId");

                    b.HasIndex("WardsId");

                    b.ToTable("ward_collectors");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.CollectionRequest", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Citizen");

                    b.Navigation("Collector");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.RewardPointTransaction", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Voucher", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.VoucherCategory", "Category")
                        .WithMany("Vouchers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.VoucherCode", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.Voucher", "Voucher")
                        .WithMany("Codes")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsedByUser");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Ward", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.Area", "Area")
                        .WithMany("Wards")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportImage", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", "WasteReport")
                        .WithMany("Images")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportItem", "WasteReportItem")
                        .WithMany("Images")
                        .HasForeignKey("WasteReportItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("WasteReport");

                    b.Navigation("WasteReportItem");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportItem", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteCategory", "WasteCategory")
                        .WithMany("ReportItems")
                        .HasForeignKey("WasteCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", "WasteReport")
                        .WithMany("Items")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WasteCategory");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportStatusHistory", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", "WasteReport")
                        .WithMany("StatusHistories")
                        .HasForeignKey("WasteReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("WasteReport");
                });

            modelBuilder.Entity("ward_collectors", b =>
                {
                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CollectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteCollection_RecyclingPlatform.Repositories.Entities.Ward", null)
                        .WithMany()
                        .HasForeignKey("WardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Area", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.Voucher", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.VoucherCategory", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteCategory", b =>
                {
                    b.Navigation("ReportItems");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReport", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Items");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("WasteCollection_RecyclingPlatform.Repositories.Entities.WasteReportItem", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
